name: Build and test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install codecov==2.0.15 flake8==3.7.9 coverage==4.5.4

    - name: Build package
      run: |
        python setup.py sdist

    - name: Test
      run: |
        python -m coverage run -m unittest discover test

    - name: Lint
      run: |
        flake8

    - name: Generate coverage report
      run: |
        coverage xml -o coverage.xml

    - name: Validate Codecov configuration
      run: |
        curl --data-binary @.codecov.yml https://codecov.io/validate | tee codecov_validation
        head -n 1 codecov_validation | grep 'Valid!'

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
